### ISSUE TITLE
在centos7 lnmpa环境下 打开install.php出以下错误

### ISSUE THREAD

**Issue by asialong** [hassiumsoft/hasscms-app#2]
Exception (#2)

An internal server error occurred.
The above error occurred while the Web server was processing your request.

Please contact us if you think this is a server error. Thank you.

**Comment by hassiumsoft** [comment]
install.php 中修改为
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');
以获得更多的错误消息

**Comment by asialong** [comment]
修改了，还是显示上面那个，没有别的提示
